version: "3.4"
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-09-23T03-47-50Z
    container_name: minio
    volumes:
      - C:\minio\data:/data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9090"

  create_buckets:
    image: minio/mc:RELEASE.2023-09-22T05-07-46Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/audios;
      /usr/bin/mc anonymous set public myminio/audios;
      exit 0;
      "
  
  postgres:
    image: postgres:16.0
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

